# Generated by Django 5.2.16 on 2026-10-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_userprofile_notify_on_access_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageaccess',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageaccess',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otpsecret',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
