# Generated by Django 5.2.16 on 2026-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_imageaccess_expires_at_imageaccess_revoked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageaccess',
            name='download_without_watermark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageaccess',
            name='shared_filename',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='imageaccess',
            name='show_watermark',
            field=models.BooleanField(default=True),
        ),
    ]
