# Generated by Django 5.2.16 on 2026-10-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_share_delivery_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageaccess',
            name='download_metadata_mode',
            field=models.CharField(choices=[('inherit', 'Same as preview'), ('include', 'Include saved metadata'), ('strip', 'Strip metadata')], default='inherit', max_length=8),
        ),
    ]
